#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Daily Briefing - Generate morning briefing for the user.

This task runs every morning at 8:00 AM and generates a briefing with:
- Today's date and day
- Pending tasks summary
- Recent activity
- Business metrics
- Any urgent items

Usage:
    python daily_briefing.py
"""

import json
import sys
from pathlib import Path
from datetime import datetime, timedelta


def generate_briefing(vault_path: Path) -> str:
    """Generate daily briefing content."""
    
    # Count files in each folder
    def count_files(folder: Path) -> int:
        try:
            return len([f for f in folder.iterdir() if f.is_file() and f.suffix == '.md'])
        except Exception:
            return 0
    
    needs_action = count_files(vault_path / 'Needs_Action')
    pending_approval = count_files(vault_path / 'Pending_Approval')
    plans = count_files(vault_path / 'Plans')
    
    # Get recent activity from logs
    recent_activity = []
    today = datetime.now().strftime('%Y-%m-%d')
    log_file = vault_path / 'Logs' / f'{today}.jsonl'
    
    if log_file.exists():
        with open(log_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()[-5:]  # Last 5 entries
            for line in lines:
                try:
                    entry = json.loads(line.strip())
                    recent_activity.append(entry)
                except json.JSONDecodeError:
                    continue
    
    # Build briefing
    now = datetime.now()
    briefing = f"""# Daily Briefing

**Date:** {now.strftime('%A, %B %d, %Y')}
**Generated:** {now.strftime('%I:%M %p')}

---

## Quick Summary

| Metric | Count |
|--------|-------|
| Pending Tasks | {needs_action} |
| Awaiting Approval | {pending_approval} |
| Active Plans | {plans} |

---

## Today's Priorities

"""
    
    # Add priorities based on counts
    if needs_action > 0:
        briefing += f"1. **Process {needs_action} pending task(s)** in Needs_Action folder\n"
    if pending_approval > 0:
        briefing += f"2. **Review {pending_approval} approval request(s)** in Pending_Approval folder\n"
    if plans > 0:
        briefing += f"3. **Check progress on {plans} active plan(s)**\n"
    
    if needs_action == 0 and pending_approval == 0:
        briefing += "*All caught up! No pending tasks or approvals.*\n"
    
    briefing += """
---

## Recent Activity

"""
    
    if recent_activity:
        briefing += "| Time | Event | Details |\n|------|-------|-------|\n"
        for activity in recent_activity:
            time = activity.get('timestamp', 'Unknown')[11:16]
            event = activity.get('event', 'Unknown')
            details = activity.get('details', {})
            details_str = str(details)[:50] if details else '-'
            briefing += f"| {time} | {event} | {details_str} |\n"
    else:
        briefing += "*No activity recorded today yet.*\n"
    
    briefing += f"""
---

## Reminders

- [ ] Review Dashboard.md for current status
- [ ] Check Pending_Approval for items needing your input
- [ ] Review any overnight emails/messages

---

## Weather & Schedule

*Add your calendar integration here*

---

*Briefing generated by AI Employee v0.2 (Silver Tier)*
"""
    
    return briefing


def main():
    """Main entry point."""
    # Get vault path
    if len(sys.argv) > 1:
        vault_path = Path(sys.argv[1])
    else:
        vault_path = Path(__file__).parent.parent / 'AI_Employee_Vault'
    
    if not vault_path.exists():
        print(f"Error: Vault path does not exist: {vault_path}")
        sys.exit(1)
    
    # Generate briefing
    briefing = generate_briefing(vault_path)
    
    # Save to Briefings folder
    briefings_folder = vault_path / 'Briefings'
    briefings_folder.mkdir(parents=True, exist_ok=True)
    
    today = datetime.now().strftime('%Y-%m-%d')
    briefing_file = briefings_folder / f'{today}_Daily_Briefing.md'
    
    briefing_file.write_text(briefing, encoding='utf-8')
    
    print(f"[Briefing] Generated: {briefing_file.name}")
    print(f"  Location: {briefing_file}")
    
    # Also print to console
    print()
    print(briefing)


if __name__ == '__main__':
    main()
